services:
  api:
    build: .
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: mongodb://mongo:27017/waiterapp
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
